<?php

return [
    /*
    |--------------------------------------------------------------------------
    | All System Permissions
    |--------------------------------------------------------------------------
    |
    */
    'all_permissions' => [
        'settings' => [
            'view_personal_information',
            'update_personal_information',
            'upload_personal_information_file',
            'download_personal_information_file',
            'view_users',
            'create_user',
            'update_user',
            'delete_user',
            'view_pawnshops',
            'update_pawnshop',
            'view_rules',
            'create_rule',
            'view_logs',
        ],
        'rates_and_categories' => [
            'view_categories',
            'create_category_rate',
            'delete_category_rate',
            'view_lump_rates',
            'create_lump_rate',
            'update_lump_rate',
            'delete_lump_rate',
            'view_category_duration',
            'create_category_duration',
            'view_subcategories',
            'create_subcategory',
            'create_subcategory_item',
            'delete_subcategory_item',
        ],
        'accounting' => [
            'view_chart_of_accounts',
            'create_chart_of_account',
            'update_chart_of_account',
            'delete_chart_of_account',
            'view_transactions',
            'export_transactions',
            'view_account_balances',
            'export_account_balances',
            'view_partner_balances',
            'export_partner_balances',
            'view_document_journals',
            'export_document_journals',
            'update_document_journal',
            'delete_document_journal',
            'restore_document_journal',
            'force_delete_document_journal',
            'search_account',
            'view_children_accounts',
        ],
        'reports' => [
            'view_v01_report',
            'view_v03_report',
            'view_v05_report',
            'view_v06_report',
            'view_v07_report',
            'view_v13_report',
            'view_v17_report',
            'export_transactions_report',
        ],
        'loans_and_deals' => [
            'view_deals',
            'update_deals',
            'delete_deal',
            'view_discounts',
            'respond_discount',
            'delete_discount',
            'attach_loan_ndm',
            'view_loan_attraction',
            'update_loan_attraction',
            'calculate_loan_interest',
            'post_loan_interest',
            'repay_loan_interest',
            'view_remaining_loan',
            'view_loan_by_journal',
        ],
        'clients' => [
            'view_clients',
            'view_client',
            'create_client',
            'update_client',
            'classify_client',
            'export_clients',
        ],
        'contracts' => [
            'view_contracts',
            'admin_view_contracts',
            'view_contract',
            'create_contract',
            'update_contract',
            'calculate_contract_interest',
            'confirm_calculated_interest',
            'export_contracts',
            'download_contract_file',
            'download_all_contract_files',
            'export_contracts_zip',
            'make_contract_payment',
            'make_full_contract_payment',
            'make_partial_contract_payment',
            'execute_contract_item',
            'view_contract_history_details',
            'pay_contract_amount',
            'request_contract_discount',
            'update_contract_number',

        ],
        'files_and_notes' => [
            'view_files',
            'upload_file',
            'download_file',
            'delete_file',
            'view_notes',
            'create_note',
            'update_note',
            'delete_note',
        ],
        'dashboard_and_orders' => [
            'view_reminder_orders',
            'create_reminder_order',
            'view_cashbox_balance',
            'create_expense',
            'create_loan_ndm',
            'add_funds',
            'view_cashbox_summary',
            'download_order',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Role Assignments
    |--------------------------------------------------------------------------
    */
    'roles' => [
        'accountant' => [
            'view_pawnshops', 'update_pawnshop', 'view_deals', 'view_discounts',
            'view_chart_of_accounts', 'create_chart_of_account', 'update_chart_of_account', 'delete_chart_of_account',
            'view_rules', 'create_rule', 'view_reminder_orders', 'create_reminder_order',
            'view_transactions', 'export_transactions', 'view_account_balances', 'export_account_balances',
            'view_partner_balances', 'export_partner_balances', 'view_document_journals', 'export_document_journals',
            'update_document_journal', 'delete_document_journal', 'restore_document_journal', 'force_delete_document_journal',
            'view_v01_report', 'view_v03_report', 'view_v05_report', 'view_v06_report', 'view_v07_report', 'view_v13_report', 'view_v17_report',
            'export_transactions_report', 'search_account', 'view_children_accounts', 'view_contracts',
            'attach_loan_ndm', 'view_loan_attraction', 'update_loan_attraction', 'calculate_loan_interest',
            'post_loan_interest', 'repay_loan_interest', 'view_remaining_loan', 'view_loan_by_journal',
            'view_cashbox_balance', 'view_clients', 'view_client', 'view_contract',
            'calculate_contract_interest', 'confirm_calculated_interest', 'export_contracts',
            'download_contract_file', 'download_all_contract_files', 'export_contracts_zip',
            'view_contract_history_details', 'view_notes', 'create_note', 'view_cashbox_summary', 'download_order',
        ],
        'manager' => [
            'view_categories', 'view_category_duration', 'view_subcategories', 'view_deals', 'view_discounts',
            'attach_loan_ndm', 'view_loan_attraction', 'update_loan_attraction', 'calculate_loan_interest',
            'post_loan_interest', 'repay_loan_interest', 'view_remaining_loan', 'view_loan_by_journal',
            'view_files', 'upload_file', 'download_file', 'view_cashbox_balance', 'create_expense',
            'create_loan_ndm', 'add_funds', 'view_clients', 'view_client', 'create_client',
            'view_contracts', 'view_contract', 'create_contract', 'calculate_contract_interest',
            'confirm_calculated_interest', 'make_contract_payment', 'make_full_contract_payment',
            'make_partial_contract_payment', 'execute_contract_item', 'view_contract_history_details',
            'pay_contract_amount', 'request_contract_discount', 'view_notes', 'create_note',
            'view_cashbox_summary', 'download_order',
        ],
    ],
];
